# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc "A macOS development environment manager"
  homepage "https://github.com/jfox85/devx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_darwin_amd64.tar.gz"
      sha256 "7fdda90f222fa5e638977250f32520ffc4f6eec3a27825aa0aca87868c97ec50"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_darwin_arm64.tar.gz"
      sha256 "88a5b50f9384e8749fa52b1fc389a40c1fd4d065c8e8a92bf713b950eccc0f65"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_linux_amd64.tar.gz"
      sha256 "7d31ad880db01859bd7da53e42fb24d1f1b71d3150f076071623d0389fbd7cb6"
      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_linux_arm64.tar.gz"
      sha256 "5c0259bfcc65cacf14dfea90ec1ae25af26de27445f821d4a6d2316ffcee2173"
      def install
        bin.install "devx"
      end
    end
  end

  test do
    system "#{bin}/devx", "--version"
  end
end
