# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc "macOS development environment manager with Git worktrees and tmux"
  homepage "https://github.com/jfox85/devx"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jfox85/devx/releases/download/v0.3.0/devx_0.3.0_darwin_amd64.tar.gz"
      sha256 "bd6c05618be2a11ccd51f732a61742d8bbbe6d9ffb5b06c7a76b25a1243fe34a"

      define_method(:install) do
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jfox85/devx/releases/download/v0.3.0/devx_0.3.0_darwin_arm64.tar.gz"
      sha256 "91aac061cf8ecee61e6adadab3ef970cf18adcd35c3dd8318c0b035113eaf989"

      define_method(:install) do
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jfox85/devx/releases/download/v0.3.0/devx_0.3.0_linux_amd64.tar.gz"
      sha256 "054abdd0c703c5bd48879aa6526c08d6d3e6aa988b3dc24caf1ba48f578b30dc"
      define_method(:install) do
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jfox85/devx/releases/download/v0.3.0/devx_0.3.0_linux_arm64.tar.gz"
      sha256 "d30218b3e24637d882451cdadb6cacb255527af0594faa4320adfd107c1b2186"
      define_method(:install) do
        bin.install "devx"
      end
    end
  end

  test do
    system bin/"devx", "--version"
  end
end
