# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc "A macOS development environment manager"
  homepage "https://github.com/jfox85/devx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_darwin_amd64.tar.gz"
      sha256 "2cdda9e7ab6c279c530e517cd17e95d049df58ae8a9396f352e5aa6132d4b315"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_darwin_arm64.tar.gz"
      sha256 "262e2979afef0c04e2a2e8c08564610ee130be1ac5cc908b93befd05b1ba6b04"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_linux_amd64.tar.gz"
      sha256 "82f00a6ea1ad0ce355be0fc3c79ef7199d4b349eecc210f58238b499d748edab"
      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jfox85/devx/releases/download/v0.1.0/devx_0.1.0_linux_arm64.tar.gz"
      sha256 "2b8a0f472d70532cc9d2b507da87590e4a53a2222ecd3a9ddf4f3be2a64ba69f"
      def install
        bin.install "devx"
      end
    end
  end

  test do
    system "#{bin}/devx", "--version"
  end
end
